# Linear regression using Numpy only

* True function : $y = 2x_1 + 3x_2 + 4$
* Single Neuron network
* Acitvation function : ReLU
* Learning rate = 0.01
* Error function: MSE

In [2]:
import numpy as np
import random

### Generating Dataset
[x1,x2,y] -> shape of data

In [3]:
dataset = np.random.rand(1000,3)

def trueFn(x1,x2):
    return 2*x1 + 3*x2 + 4

dataset[:, 2] = trueFn(dataset[:, 0], dataset[:, 1])
    
print(dataset)

[[0.91097889 0.85483822 8.38647245]
 [0.38648833 0.89396704 7.4548778 ]
 [0.65367278 0.05882391 5.48381731]
 ...
 [0.92761536 0.76903424 8.16233345]
 [0.60857333 0.59169459 6.99223045]
 [0.97438011 0.31907136 6.9059743 ]]


### Grad functions

In [4]:
def update_w(learning_rate, t, y, a, x) -> float:
    d_a_y = np.where(a > 0, 1, 0)
    return learning_rate * np.mean((t - y) * d_a_y * x)

def update_b(learning_rate, t, y, a) -> float:
    d_a_y = np.where(a > 0, 1, 0)
    return learning_rate * np.mean((t - y) * d_a_y)

def reLU(a):
    return np.maximum(a, 0)

### Running the model

In [5]:
w1=random.random()
w2=random.random()
b=random.random()
learning_rate = 0.01

epochs = 10000
for i in range(epochs):
    a = w1 * dataset[:, 0] + w2 * dataset[:, 1] + b
    y = reLU(a)
    w1 += update_w(learning_rate, dataset[:, 2], y, a, dataset[:, 0])
    w2 += update_w(learning_rate, dataset[:, 2], y, a, dataset[:, 1])
    b  += update_b(learning_rate, dataset[:, 2], y, a)
    
print("Final weights: ",w1,w2,b)

Final weights:  1.998079710302264 2.997786939069709 4.002198086725567
